services:
  web:
    build: 
      context: ./queueproto
      dockerfile: Dockerfile
    command: uvicorn queueproto.wsgi:fastapp_v1 --host 0.0.0.0
    volumes:
      - ./queueproto/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./queueproto/.env.docker
    depends_on:
      - redis

  celery-single-worker:
    build:
      context: ./queueproto
      dockerfile: Dockerfile
    command: celery -A queueproto worker --loglevel=INFO --concurrency=1 -Q single_worker_queue
    volumes:
      - ./queueproto/:/usr/src/app/
    env_file:
      - ./queueproto/.env.docker
    depends_on:
      - redis

  celery-beat:
    build:
      context: ./queueproto
      dockerfile: Dockerfile
    command: celery -A queueproto beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./queueproto/:/usr/src/app/
    env_file:
      - ./queueproto/.env.docker
    depends_on:
      - redis

  redis:
    image: redis:alpine
    expose:
      - 6379
