tailwind:
	npx tailwindcss -i ./static/src/input.css -o ./static/src/output.css --watch

rund:
	python3 manage.py runserver

runs:
	python3 run.py

run:
	python3 run.py & npx tailwindcss -i ./static/src/input.css -o ./static/src/output.css --watch
